website/converter/urls.py
from django.urls import path

from . import views


app_name = 'converter'

urlpatterns = [
    path('', views.upload_video, name='index'),
    path('profile/<username>/', views.ProfileDetailView.as_view(), name='profile'),
    path('download_file/<str:file_path>/', views.download_audio, name='download_file')
]

website/pages/urls.py
from django.urls import path

from . import views


app_name = 'pages'


urlpatterns = [
    path('about/', views.AboutTemplateView.as_view(), name='about')
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('converter:index'),
        ),
        name='registration',
    ),
    path('', include('converter.urls', namespace='converter')),
    path('pages/', include('pages.urls', namespace='pages')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/converter/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Video(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name='Название',
        help_text='Придумайте название будущему файлу'
    )
    video_file = models.FileField(
        upload_to='videos/',
        verbose_name='Место загрузки файла',
        help_text=(
            'Выберите файл на вашем'
            ' компьютере для получения аудио'
        )
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'видео'
        verbose_name_plural = 'Видео'

website/pages/models.py
from django.db import models

# Create your models here.

website/converter/forms.py
from django import forms

from .models import Video


class VideoForm(forms.ModelForm):
    """Форма для видео."""

    class Meta:
        model = Video
        fields = '__all__'

website/converter/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse
from django.shortcuts import render
from django.views.generic import DetailView
import os

import moviepy.editor as mp

from .forms import VideoForm
from .models import User


def upload_video(request):
    # Алгоритм преобразования
    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)

        if form.is_valid():
            video = form.save()
            video_path = video.video_file.path
            audio_path = video_path.replace('.mp4', '.mp3')
            clip = mp.VideoFileClip(video_path)
            clip.audio.write_audiofile(audio_path, codec='mp3')
            os.rename(
                audio_path,
                f'T:\\tests_pyhton\\website_extract_audio_from_video\\website\\media\\videos\\{video.title}.mp3'
            )
            if os.path.exists(audio_path):
                os.remove(audio_path)
            audio_path = f'T:\\tests_pyhton\\website_extract_audio_from_video\\website\\media\\videos\\{video.title}.mp3'
            context = {
                'audio_path': audio_path,
            }
            return render(
                request,
                'converter/success.html',
                context
            )
    else:
        form = VideoForm()
        return render(
            request,
            'converter/upload_video.html',
            {'form': form}
        )


class ProfileDetailView(LoginRequiredMixin, DetailView):
    """Детальное отображение пользователя."""

    model = User
    slug_url_kwarg = 'username'
    slug_field = 'username'
    context_object_name = 'profile'
    template_name = 'converter/profile.html'


def download_audio(request, file_path):
    # Отправка файла пользователю для загрузки
    response = FileResponse(open(file_path, 'rb'), as_attachment=True)
    return response

website/pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class AboutTemplateView(TemplateView):

    template_name = 'pages/about.html'

website/templates/base.html
<!doctype html>
<html lang="en">
<head>
  {% load static %}
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
    {% block title %}

    {% endblock %}
  </title>
</head>
<body>
  {% include "includes/header.html" %}
  {% block content %}

  {% endblock %}
</body>
</html>

website/templates/converter/profile.html
{% extends "base.html" %}

{% block title %}
  Личный кабинет пользователя profile.username
{% endblock %}

{% load django_bootstrap5 %}

{% block content %}
  <div class="container mt-5 col-5">
    <div class="card">
      <div class="card-body">
        <p>Имя пользователя: {{ profile.username }}</p>
        {% if profile.email %}
          <p>Почта: {{ profile.email }}</p>
        {% else %}
          <p>Почта: отсутствует</p>
        {% endif %}
        <a href="{% url 'logout' %}">
          {% bootstrap_button button_type="submit" content="Выйти из аккаунта" %}
        </a>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/converter/success.html
{% extends "base.html" %}

{% block title %}
  Форматирование завершено успешно
{% endblock %}

{% load django_bootstrap5 %}

{% block content %}
  <div class="container mt-5">
    <h3 class="mb-3">Получение аудио-файла прошло успешно!</h3>
    <audio controls>
      <source src="{{ audio_path }}" type="audio/mpeg">
      Ваш браузер не поддерживает этот формат аудио.
    </audio>
    <form method="post"
          action="{% url 'converter:download_file' audio_path %}"
          enctype="multipart/form-data" class="mt-3">
      {% csrf_token %}
      {% bootstrap_button button_type="submit" content="Скачать аудио" %}
    </form>
  </div>
{% endblock %}

website/templates/converter/upload_video.html
{% extends "base.html" %}

{% block title %}
  Получение из видео аудио дорожку. Главная страница
{% endblock %}

{% load django_bootstrap5 %}

{% block content %}
  <div class="container mt-5 col-7">
    {% if user.is_authenticated %}
      <h3>Загрузите видео</h3>
      <hr>
      <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Загрузить" %}
      </form>
    {% else %}
      <h3>
        <a href="{% url 'login' %}">Войдите в аккаунт</a>
        или <a href="{% url 'registration' %}">
        зарегистрируйтесь</a>, чтобы воспользоваться сервисом!
      </h3>
    {% endif %}
  </div>
{% endblock %}

website/templates/includes/header.html
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'converter:index' %}" class="nav-link px-2 text-secondary">Главная</a></li>
        <li><a href="{% url 'pages:about' %}" class="nav-link px-2 text-white">О нас</a></li>
      </ul>
      <div class="text-end">
        {% if request.user.is_authenticated %}
          <a href="{% url 'converter:profile' user.username %}">
            <button type="button" class="btn btn-outline-light me-2">
              Личный кабинет
            </button>
          </a>
        {% else %}
          <a href="{% url 'login' %}">
            <button type="button" class="btn btn-outline-light me-2">
              Войти
            </button>
          </a>
          <a href="{% url 'registration' %}">
            <button type="button" class="btn btn-warning">
              Регистрация
            </button>
          </a>
        {% endif %}
      </div>
    </div>
  </div>
</header>

website/templates/pages/about.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block title %}
  Страница о нас
{% endblock %}

{% block content %}
  <div class="container mt-5 col-7">
    <h3>Страница о нас</h3>
    <hr>
    <p class="mt-3">Вам предоставляется онлайн-конвертер видео при помощи которого можно быстро получить аудио-дорожку</p>
    <p>Наш сервис поддерживает такие форматы как: .MP4</p>
    <p>Как пользоваться нашим сервисом? Все очень просто!</p>
    <ol>
      <li>Необходимо зарегистрироваться или войти в уже существующий аккаунт</li>
      <li>Вставить загруженное видео в поле и нажать загрузить!</li>
      <li>После какого-то времени загрузить полученную аудиодорожку и наслаждаться звуком</li>
    </ol>
    <h5>Спасибо, что выбрали наш сервис!)</h5>
  </div>
{% endblock %}